server:
  port: 8082
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
  rabbitmq:
    host: ${RABBIT_HOST}
    port: 5672
    username: ${RABBIT_ID}
    password: ${RABBIT_PASSWORD}
    virtual-host: app-vhost

  jackson:
    time-zone: Asia/Seoul
    serialization:
      write-dates-as-timestamps: true

rabbit:
  events:
    exchange: lxp.events
    routing-prefix: lxp.
    queues:
      user:
        name: notification.events.q
        bindings:
          - lxp.user.created
          - lxp.user.verified
      purchase:
        name: purchase.events.q
        bindings:
    dlq:
      dlx: lxp.events.dlx
      name: lxp.events.dlq
      routing: lxp.events.dlq